SRC_URI_append = "								\
	file://0001-cl-som-imx8x-add-basic-support.patch			\
	file://0002-sb-imx8x-add-basic-support.patch				\
	file://0003-startek-ili9881c-Add-panel-driver.patch			\
	file://0004-startek-ili9881c-cl-som-imx8x-add-panel-support.patch	\
	file://0005-sb-imx8x-add-support-to-Omnivision-OV5640.patch		\
	file://0006-sb-imx8x-enable-the-Goodix-touch-panel.patch		\
	file://0007-sb-imx8x-add-mipi-panel-backlight.patch			\
	file://0008-cl-som-imx8x-release-kernel-v5.4.70-cl-som-imx8x-2.0.patch	\
	file://defconfig							\
"
